src/modules/auth/auth.controller.ts
src/modules/auth/auth.service.ts
src/modules/auth/dto/login.dto.ts

[INV-18] Create login endpoint

---

src/modules/user/entities/account.entity.ts
src/modules/wishlists/entities/wishlist.entity.ts

[INV-66] Fix "column type specified more than once" error when registering & fix wishlist entity mapping errors

---

src/app.module.ts
src/modules/accommodations/entities/accommodations.entity.ts
src/modules/wishlists/dto/create-wishlist.dto.ts
src/modules/wishlists/wishlist.controller.ts
src/modules/wishlists/wishlist.service.ts
src/modules/wishlists/wishlists.module.ts
src/shared/guards/roles.guard.ts

POST /wishlists
GET /wishlists
GET /wishlists => when the user isn't admin
GET /wishlists/:id
DELETE /wishlists/:id

[INV-48] Create Wishlist CRUD & fix accommodation entity problem & fix roles guard

---

database/migrations/1731453916450-remove-status-column-from-accommodation-table.ts
database/migrations/1731488129790-update-accommodation-address-table.ts
database/migrations/1731498135557-update-accommodation-amenity-table.ts
src/modules/accommodations/accommodations.module.ts
src/modules/accommodations/controllers/accommodations.controller.ts
src/modules/accommodations/dto/requests/create-accommodation-address.req.ts
src/modules/accommodations/dto/requests/create-accommodation-amenity.req.ts
src/modules/accommodations/dto/requests/create-accommodation-image.req.ts
src/modules/accommodations/dto/requests/create-accommodation.req.ts
src/modules/accommodations/entities/accommodation-address.entity.ts
src/modules/accommodations/entities/accommodation-amenity.entity.ts
src/modules/accommodations/entities/accommodation-image.entity.ts
src/modules/accommodations/entities/accommodations.entity.ts
src/modules/accommodations/services/accommodation-address.service.ts
src/modules/accommodations/services/accommodation-amenity.service.ts
src/modules/accommodations/services/accommodation-image.service.ts
src/modules/accommodations/services/accommodations.service.ts
src/modules/auth/types/express.d.ts

Post <img width="2168" alt="Screenshot 2024-11-13 at 19 38 37" src="https://github.com/user-attachments/assets/0deb3ae7-aadd-4c49-977e-3d705477bce3">
Result <img width="2168" alt="Screenshot 2024-11-13 at 19 38 44" src="https://github.com/user-attachments/assets/dee86386-a7ed-40ba-9569-3d05458a367f">

[INV-68]-Create method-to-create-accommodation

---

src/shared/configs/swagger.config.ts

[INV-74] Add bearer auth to Swagger

---

src/modules/accommodations/controllers/accommodations.controller.ts
src/modules/accommodations/services/accommodations.service.ts

https://github.com/user-attachments/assets/9de41e6f-1088-4ddc-844c-6cfa593b23f5

[INV-78]-Implement CRUD operations for Accommodation/GetById

---

database/migrations/1731928957503-add-deletedAt-to-accommodation.ts
src/modules/accommodations/controllers/accommodations.controller.ts
src/modules/accommodations/entities/accommodations.entity.ts
src/modules/accommodations/services/accommodations.service.ts

https://github.com/user-attachments/assets/8ac3f1ff-b779-4214-94a3-193e46bee321

[INV-71]-Implement-CRUD-operations-for-Accommodation/delete

---

.dockerignore
Dockerfile
README.md
docker-compose.yml
tsconfig.json

Add Docker & Docker compose for BE

---

src/modules/accommodations/controllers/accommodations.controller.ts
src/modules/accommodations/services/accommodations.service.ts

added total field to the method get listAccommodations

[INV-44] - Add total to get listAccommodations

---

.eslintrc.js
database/migrations/1731928957503-add-deletedAt-to-accommodation.ts
database/migrations/1731996224488-create-booking-table.ts
src/modules/bookings/entities/booking.entity.ts
src/shared/configs/database.config.ts
src/shared/constants/booking-status.constant.ts

[INV-59] Create booking table migration + entity & module

---

src/modules/accommodations/controllers/accommodations.controller.ts
src/modules/accommodations/dto/requests/accommodation-filters.req.ts
src/modules/accommodations/helpers/accommodation-filters.util.ts
src/modules/accommodations/services/accommodations.service.ts
src/modules/accommodations/utils/pagination-params.util.ts
src/modules/accommodations/utils/sort-by-params.util.ts
src/shared/constants/pagination.constant.ts
src/shared/types/base-response.type.ts
src/shared/types/pagination.type.ts
src/shared/utils/pagination-offset.util.ts
src/shared/utils/pagination.util.ts
src/shared/utils/with-base-response.util.ts

created withBaseResponse function
created method that returns pagination metadata

[INV-84] - With base response function

---

database/migrations/1732127232754-create-review-entity.ts
src/modules/review/entities/review.entity.ts
src/modules/review/review.module.ts

[INV-86] Create review module, entity and migration

---

src/modules/accommodations/controllers/accommodations.controller.ts
src/modules/accommodations/services/accommodations.service.ts
src/modules/accommodations/tests/accommodations.service.spec.ts

https://github.com/user-attachments/assets/3a07254e-1f0f-42c1-84e5-db8840a7bb15

[INV-99]-Get-reviews-of-accommodation

---

package-lock.json
package.json
src/modules/accommodations/entities/accommodations.entity.ts
src/modules/accommodations/services/accommodations.service.ts
src/modules/accommodations/tests/accommodations.service.spec.ts
src/modules/bookings/services/bookings.service.ts

Fixed getAccommodationById in accommodations service so that we can get unavailable dates and ect

INV-52/add-booking-logic/backendFix

---

src/modules/review/dto/create.review.dto.ts

AccommodationId is actually coming from bookingId, I forgot to remove that

Fix: remove AccommodationId from CreateReviewDto

---

.github/workflows/main.yml

Updated deploy script in github workflow main.yml file

[INV-26] deploy to vps small update in script command

---

.env.example
src/modules/uploads/services/minio.service.ts
src/modules/uploads/services/uploads.service.ts
src/shared/configs/env.config.ts

I fixed all the service issues related to Minio Service.
_Please replace this text with a description of the changes in this PR or attach a screenshots/video of the changes._

[INV-109] Fix MinIO service issue

---

src/modules/bookings/bookings.controller.ts
src/modules/bookings/bookings.service.ts
src/modules/bookings/dto/request/update-booking-status.req.ts
src/modules/payments/services/stripe.service.ts
src/modules/payments/tests/stripe.service.spec.ts

- Created update booking status controller
- Fixed update status service

[INV-105] Create Booking Card

---

database/migrations/1733832547997-create-category-table.ts
database/migrations/1733832599964-create-accommodation-category-joint-table.ts
src/app.module.ts
src/modules/accommodations/dto/request/accommodation-filters.req.ts
src/modules/accommodations/entities/accommodation.entity.ts
src/modules/accommodations/services/accommodations.service.ts
src/modules/categories/categories.controller.ts
src/modules/categories/categories.module.ts
src/modules/categories/categories.service.ts
src/modules/categories/dto/requests/cretae-category.req.ts
src/modules/categories/entities/categories.entity.ts
src/modules/categories/tests/categories.service.spec.ts
src/shared/configs/database.config.ts

- created Category module 
- implemented create and read operations for categories 
- generated migrations for category and accommodation-categories joint tables 
- added filter for getting listAccommodations that match provided category 
- wrote tests
Create a category:
Get categories:
Get accommodations by specific category:
Categories table:

[INV-113] Add categories to accommodations

---

src/modules/reviews/dto/request/create-review.req.ts
src/modules/reviews/tests/review.service.spec.ts

_Please replace this text with a description of the changes in this PR or attach a screenshots/video of the changes._

Fix: remove accommodationId from review dto

---

src/modules/reviews/dto/request/update-review.req.ts
src/modules/reviews/reviews.controller.ts
src/modules/reviews/reviews.service.ts
src/modules/reviews/tests/fixtures/reviews-data.mock.ts
src/modules/reviews/tests/review.service.spec.ts
src/modules/users/users.controller.ts

- Added GET endpoint to get user reviews
- Added PUT endpoint to update comment by author
- Added DELETE endpoint to delete comment by author

[INV-82,85,122] Review endpoints

---

src/modules/accommodations/services/accommodations.service.ts

Fixed create accommodation service

---

src/modules/accommodations/services/accommodations.service.ts
src/modules/accommodations/tests/accommodations.service.spec.ts
src/modules/payments/dto/request/checkout.req.ts
src/modules/payments/services/stripe.service.ts
src/shared/transformers/transform-type.transformer.ts

- Fixed datepickers
- Fixed stripe error
- Added owner to getAccommodationById service
- Added reviews to listAccommodations service

[INV-133] Fixing bugs and little changes

---

src/modules/accommodations/entities/accommodation.entity.ts
src/modules/accommodations/services/accommodations.service.ts

Added fake User

---

src/modules/accommodations/controllers/accommodations.controller.ts
src/modules/accommodations/services/accommodations.service.ts

Get accommodations created by user in my accommodations page

[INV-98] - Owner accommodations
